version: "3.8"
services:
  Lokesh_mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: Lokesh_mariadb
    environment:
      - MYSQL_DATABASE:baseball
      - MYSQL_ROOT_PASSWORD=1196
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1196
    volumes:
      - mariadb:/config
    ports:
      - "8000:3306"
    restart: unless-stopped

  Lokesh_mysql:
    container_name: mysql_hw_06
    image: mysql_service
    build:
      context: .
      dockerfile: assignment_06/Dockerfile
    depends_on:
      - Lokesh_mariadb
    volumes:
      - ./assignment_06/result:/app/output
#    environment:
#      - DB_HOST=Lokesh_mariadb
#      - DB_PORT=3306
volumes:
  mariadb:
    driver: local
